# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "=1.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0-beta.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0-beta.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0-beta.2"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
